### ISSUE TITLE
Insufficient buffer

### ISSUE THREAD

**Issue by ivankennethwang** [tomkp/smartcard#4]
Error in reading response from smart card reader. I am just translating this python code, https://gist.github.com/bouroo/8b34daf5b7deed57ea54819ff7aeef6e, to node.

(node:61981) UnhandledPromiseRejectionWarning: Error: SCardTransmit error: Insufficient buffer.(0x80100008)

```
const _ = require('lodash');
const smartcard = require('smartcard');
const Devices = smartcard.Devices;

// Check card
const SELECT = [0x00, 0xA4, 0x04, 0x00, 0x08]
const THAI_CARD = [0xA0, 0x00, 0x00, 0x00, 0x54, 0x48, 0x00, 0x01]

// CID
const CMD_CID = [0x80, 0xb0, 0x00, 0x04, 0x02, 0x00, 0x0d]

// Photo_Part1/20
const CMD_PHOTO1 = [0x80, 0xb0, 0x01, 0x7B, 0x02, 0x00, 0xFF]

function clean(str) {
  return str.replace(/[^\w\s]/gi, ' ').replace(/\s\s+/g,' ').trim();
}

devices.on('device-activated', event => {
  const currentDevices = event.devices;
  let device = event.device;
  console.log(`Device '${device}' activated, devices: ${currentDevices}`);
  for (let prop in currentDevices) {
    console.log("Devices: " + currentDevices[prop]);
  }

  device.on('card-inserted', async (event) => {
    let card = event.card;
    let atr = card.getAtr();

    console.log(`ATR: ${atr}`)

    card.on('command-issued', event => {
      console.log(`>> ${event.command}`);
    });

    card.on('response-received', event => {
      console.log(`<< ${event.response}`);
    });

    req = [0x00, 0xc0, 0x00, 0x00];
    if (atr.substring(0,2) == '3b' && atr.substring(2,4) == '67') {
      req = [0x00, 0xc0, 0x00, 0x01];
    }

    const SELECT_THAI_CARD = _.flatten([SELECT, THAI_CARD]);
    // SELECT THAI CARD
    await card.issueCommand(SELECT_THAI_CARD);

    await card.issueCommand(CMD_CID);
    const CMD_CID_REAL = _.flatten([req, CMD_CID[CMD_CID.length - 1]]);
    let cid = await card.issueCommand(CMD_CID_REAL);
    console.log(`[${clean(new Buffer(cid, 'tis-620').toString('utf-8'))}]`);

    await card.issueCommand(CMD_PHOTO1);
    const CMD_PHOTO1_REAL = _.flatten([req, CMD_PHOTO1[CMD_PHOTO1.length - 1]]);
    let photo = await card.issueCommand(CMD_PHOTO1_REAL);
    console.log(photo);
  });
  device.on('card-removed', event => {
    console.log(`Card removed from '${event.name}' `);
  });

});

devices.on('device-deactivated', event => {
  console.log(`Device '${event.device}' deactivated, devices: [${event.devices}]`);
});
```

```node index.js
Device 'Generic Smart Card Reader Interface' activated, devices: Generic Smart Card Reader Interface
Devices: Generic Smart Card Reader Interface
ATR: HIDDEN
>> 0,164,4,0,8,160,0,0,0,84,72,0,1
<< HIDDEN
>> 128,176,0,4,2,0,13
<< HIDDEN
>> 0,192,0,0,13
<< HIDDEN
[HIDDEN]
>> 128,176,1,123,2,0,255
<< HIDDEN
>> 0,192,0,0,255
(node:61981) UnhandledPromiseRejectionWarning: Error: SCardTransmit error: Insufficient buffer.(0x80100008)
(node:61981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ivankennethwang** [comment]
```/Users/ivan/experiments/cardreader/node_modules/smartcard/lib/ResponseApdu.js:53
        this.data = buffer.toString('hex');
                           ^

TypeError: Cannot read property 'toString' of undefined
    at new ResponseApdu (/Users/ivan/experiments/cardreader/node_modules/smartcard/lib/ResponseApdu.js:53:28)
    at /Users/ivan/experiments/cardreader/node_modules/smartcard/lib/Card.js:79:35```

**Comment by sgnsys3** [comment]
Hello I have same problem. When getting photo record that expect 0xFF response length. I trick it with resize to 0xFD The error was solve but the picture is corrupt.

Are you Implement Thailand Citizen Smartcard reader ?
You can contribute with me https://github.com/sgnsys3/thaismartcardreader.js

**Comment by sgnsys3** [comment]
@ivankennethwang Now you can use version smartcard@1.0.23 they increase the buffer size.
Try 
```yarn upgrade```

**Comment by ivankennethwang** [comment]
Cool thanks. @sgnsys3 yup im building one. Happy to help.
